"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ins_t(object):

    __slots__ = ["time", "week", "utcTime", "insStatus", "yaw", "pitch", "roll", "latitude", "longitude", "altitude", "nedVelX", "nedVelY", "nedVelZ", "attUncertainty", "posUncertainty", "velUncertainty"]

    __typenames__ = ["double", "int32_t", "int64_t", "int32_t", "float", "float", "float", "double", "double", "double", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None, None, [3], None, None]

    def __init__(self):
        self.time = 0.0
        """ LCM Type: double """
        self.week = 0
        """ LCM Type: int32_t """
        self.utcTime = 0
        """ LCM Type: int64_t """
        self.insStatus = 0
        """ LCM Type: int32_t """
        self.yaw = 0.0
        """ LCM Type: float """
        self.pitch = 0.0
        """ LCM Type: float """
        self.roll = 0.0
        """ LCM Type: float """
        self.latitude = 0.0
        """ LCM Type: double """
        self.longitude = 0.0
        """ LCM Type: double """
        self.altitude = 0.0
        """ LCM Type: double """
        self.nedVelX = 0.0
        """ LCM Type: float """
        self.nedVelY = 0.0
        """ LCM Type: float """
        self.nedVelZ = 0.0
        """ LCM Type: float """
        self.attUncertainty = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.posUncertainty = 0.0
        """ LCM Type: float """
        self.velUncertainty = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(ins_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">diqifffdddfff", self.time, self.week, self.utcTime, self.insStatus, self.yaw, self.pitch, self.roll, self.latitude, self.longitude, self.altitude, self.nedVelX, self.nedVelY, self.nedVelZ))
        buf.write(struct.pack('>3f', *self.attUncertainty[:3]))
        buf.write(struct.pack(">ff", self.posUncertainty, self.velUncertainty))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ins_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ins_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ins_t()
        self.time, self.week, self.utcTime, self.insStatus, self.yaw, self.pitch, self.roll, self.latitude, self.longitude, self.altitude, self.nedVelX, self.nedVelY, self.nedVelZ = struct.unpack(">diqifffdddfff", buf.read(72))
        self.attUncertainty = struct.unpack('>3f', buf.read(12))
        self.posUncertainty, self.velUncertainty = struct.unpack(">ff", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ins_t in parents: return 0
        tmphash = (0xc0784782b8273dce) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ins_t._packed_fingerprint is None:
            ins_t._packed_fingerprint = struct.pack(">Q", ins_t._get_hash_recursive([]))
        return ins_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ins_t._get_packed_fingerprint())[0]

